color0 #26282c
color1 #fd4663
color2 #a2a4aa
color3 #94949e
color4 #97949e
color5 #bcbec2
color6 #bcbcc2
color7 #f2f2f3
color8 #66686f
color9 #fd4663
color10 #a2a4aa
color11 #94949e
color12 #97949e
color13 #bcbec2
color14 #bcbcc2
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #1c1e21
background            #1c1e21
foreground            #f2f2f3
selection_foreground  #b0b2b5
selection_background  #26282c
active_border_color   #a2a4aa
inactive_border_color #26282c
url_color             #a2a4aa

active_tab_foreground   #18191d
active_tab_background   #a2a4aa
inactive_tab_foreground #b0b2b5
inactive_tab_background #26282c
cursor_trail_color      #b0b2b5
