color0 #22272f
color1 #fd4663
color2 #8b9dc1
color3 #8981b1
color4 #a085ad
color5 #acb9d3
color6 #b4afd0
color7 #f2f2f3
color8 #626872
color9 #fd4663
color10 #8b9dc1
color11 #8981b1
color12 #a085ad
color13 #acb9d3
color14 #b4afd0
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #1a1d23
background            #1a1d23
foreground            #f2f2f3
selection_foreground  #afb1b6
selection_background  #22272f
active_border_color   #8b9dc1
inactive_border_color #22272f
url_color             #8b9dc1

active_tab_foreground   #1b1d22
active_tab_background   #8b9dc1
inactive_tab_foreground #afb1b6
inactive_tab_background #22272f
cursor_trail_color      #afb1b6
